### ISSUE TITLE
convergence failure when pass band partitioned

### ISSUE THREAD

**Issue by jlwehle** [sfilip/firpm#10]
This test case has two specifications both with identical pass and stop bands ... the difference being the first specification has its pass band partitioned.

With the test case built like so:

```
  clang++ -I/usr/local/include -O2 -march=amdfam10
    -o firpm-tc-10ka firpm-tc-10ka.cxx
    -L/usr/local/lib -lfirpm -lmpfr -lgmp
```

Running it results in:

```
  START Parks-McClellan with uniform initialization
  WARNING: The exchange algorithm did not converge.
  TRIGGER: Not enough alternating extrema!
  POSSIBLE CAUSE: Nmax too small
  WARNING: The exchange algorithm did not converge.
  TRIGGER: numerical instability
  POSSIBLE CAUSES: poor starting reference and/or a too small value for Nmax.
  Iteration count = NC
  FINISH Parks-McClellan with uniform initialization

  START Parks-McClellan with uniform initialization
  Final delta     = 1.4049544582785901791e-05
  Iteration count = 55
  FINISH Parks-McClellan with uniform initialization
```

What's interesting is the two filter specifications are very similar ... firpm fails for the first specification and succeeds for the second.

Perhaps this is just the nature of things ... anyway I pass this along in case comparing / contrasting the two behaviors suggests something.
[firpm-tc-10ka.cxx.txt](https://github.com/sfilip/firpm/files/3909227/firpm-tc-10ka.cxx.txt)

**Comment by sfilip** [comment]
Thanks! Didn't really take the partitioned case into account as a possible scenario. I will try to have a commit soon with a fix.

**Comment by sfilip** [comment]
OK, added support for partitioned bands and accompanying tests. Hopefully it works in most of the cases that you are looking at. On both the examples from this issue and #11 the code should now work for all three versions of firpm and choice of arithmetic (except one of the examples that still does not work with uniform initialization and double precision -- this is due to numerical problems that I can't really do anything about).

Out of curiosity, I looked if Matlab's version of PM supports partitioned bands and it doesn't. Guess this is why I didn't focus on this setting initially... In any case, thanks for spotting all these particular instances that I didn't really think about.

**Comment by jlwehle** [comment]
That was quick.

I'm glad that the feedback is useful.  I'm working on a personal project and a novice regarding fir filters which causes me to try things that a more experienced person might know better than to do. :-)

Anyway, of the three different open source firpm implementations I tried yours seems to be the most capable.
