### ISSUE TITLE
Patch - On failure return to the caller instead of exiting the program

### ISSUE THREAD

**Issue by jlwehle** [sfilip/firpm#12]
It's a bit inconvenient to have firpm terminate the calling program upon failure.  Some of my samples converge successfully using firpmRS and not firpmAFP, others converge successfully using firpmAFP and not firpmRS.

The attached patch changes the firpm library so that it internally throws exceptions instead of exiting.  This allows the caller to see that a failure occurred (indicated by the value of output.q), giving the caller a chance to decide how it should handle the failure (i.e. perhaps by retrying with a different initialization approach).

The supplied change is just a quick minimal approach ... it might be useful to provide the failure code to the caller.  Another useful change might be to accept an error stream parameter instead of assuming that it's okay to write to std::cerr.
[firpm-sfilip-PatchJLW02.txt](https://github.com/sfilip/firpm/files/3986918/firpm-sfilip-PatchJLW02.txt)

**Comment by sfilip** [comment]
Thanks. Added exceptions instead of forced termination and introduced a `status` code that will be written into the return `pmoutput_t` object. 

I will probably add an option to specify the output error stream, but I'm holding off on it for now. I want to add firpm as a dependency for fquantizer and will make these interface changes when I start working on that.
