### ISSUE TITLE
firpm RS generates NaN coefficients for certain specifications

### ISSUE THREAD

**Issue by jlwehle** [sfilip/firpm#13]
Compiling firpm-tc-50ka like so:

```
  clang++ -I/usr/local/include -O2 -march=amdfam10 -DHAVE_MPFR \
    -o firpm-tc-50ka firpm-tc-50ka.cxx -L/usr/local/lib -lfirpm -lmpfr -lgmp
```

and then running it results in:

```
  Filter degree 482
  START Parks-McClellan with uniform initialization
  Final delta     = 5.88012e-05
  Iteration count = 32
  FINISH Parks-McClellan with uniform initialization
  START Parks-McClellan with reference scaling
  Final delta     = 5.90794e-05
  Iteration count = 9
  FINISH Parks-McClellan with reference scaling
  START Parks-McClellan with AFP
  Final delta     = 5.94789e-05
  Iteration count = 8
  FINISH Parks-McClellan with AFP
  Iteration reduction for final filter  RS: 0.71875
  Iteration reduction for final filter AFP: 0.75
```

however looking at the resulting files:

```
  firpm-tc-50ka-UNI-coeff.txt
  firpm-tc-50ka-RS-coeff.txt
  firpm-tc-50ka-AFP-coeff.txt
```

shows all the RS coefficients are NaN.

[firpm-tc-50ka.cxx.txt](https://github.com/sfilip/firpm/files/3989565/firpm-tc-50ka.cxx.txt)

**Comment by jlwehle** [comment]
Here's a potentially related example using uniform initialization with the same two bands.

Compiling firpm-tc-50kb like so:

```
  clang++ -I/usr/local/include -O2 -march=amdfam10 -DHAVE_MPFR \
    -o firpm-tc-50kb firpm-tc-50kb.cxx -L/usr/local/lib -lfirpm -lmpfr -lgmp
```

and then running it results in:

```
  Filter degree 482
  START Parks-McClellan with uniform initialization
  Final delta     = 5.45619e-05
  Iteration count = 26
  FINISH Parks-McClellan with uniform initialization
```

however graphing the resulting coefficients:

`  firpm-tc-50kb-UNI-coeff.txt
`
doesn't show the proper response as can be seen in:

`  firpm-50k.png
`
For comparison the coefficients generated in Octave by:

```
  win = kaiser(483, 8.2);
  b = fir2(482, [0, 0.0532, 0.1468, 1], [1, 1.01, 0, 0], win);
```

can be seen in:

`  octave-fir2-50k.png`

If I change the magnitude vector to be [1, 1, 0, 0] then firpm
generates the expected response.

![firpm-50k](https://user-images.githubusercontent.com/46985578/71302772-54465100-237d-11ea-9d91-d492e876a360.png)
[firpm-tc-50kb.cxx.txt](https://github.com/sfilip/firpm/files/3991043/firpm-tc-50kb.cxx.txt)
[firpm-tc-50kb-UNI-coeff.txt](https://github.com/sfilip/firpm/files/3991044/firpm-tc-50kb-UNI-coeff.txt)
![octave-fir2-50k](https://user-images.githubusercontent.com/46985578/71302773-54465100-237d-11ea-88a7-b465b62df510.png)

**Comment by jlwehle** [comment]
Regarding firpm-tc-50ka (which generates NaN for RS) tracing through the code we call approx towards the end of exchange.  At the end of approx is:

`  Pc = num / denom;`

Unfortunately denom is zero in some cases so Pc is set to -inf and things go downhill from there.

**Comment by sfilip** [comment]
Hi! Thanks for spotting this. 

There are several things I'd like to comment on. 

For the NaN problem I have to do some tests to see when and how exactly it starts cropping up. I'll see if there is anything I can do to take care of it. In case I cannot eliminate it, I will probably raise an exception and put in place a mechanism like what you suggested in #12 .

The filter specifications are a bit peculiar, in the sense that if I change the magnitude vector to [1, 1, 0, 0], the final delta with an 483 tap firpm filter is extremely small (of the order of double precision machine epsilon). In that case, I don't trust a frequency response plot since I expect the result to be highly sensitive to any changes in the filter tap values (e.g. due to rounding). For instance this is the frequency response plot (the top one) I get with Matlab's `freqz` function:

![firpm483_ 1_1_0_0](https://user-images.githubusercontent.com/12035795/72615591-62b06a00-3935-11ea-8910-c927124dbd95.png)

The equioscillatory behavior typical for PM-generated filters is clearly not visible. On the other hand if I take a smaller length filter, for instance with 203 taps, I get a nice plot with clear equioscillatory behavior in the [0.1468, 1.0] stopband:

![firpm203_ 1_1_0_0](https://user-images.githubusercontent.com/12035795/72615974-2f220f80-3936-11ea-85ac-b4126aff3dee.png)

Changing the magnitude vector to [1.0, 1.01, 0.0, 0.0], the final delta for a 483 tap filter is now much larger, but the same frequency response problem persists:

![firpm483_ 1_1 01_0_0](https://user-images.githubusercontent.com/12035795/72618987-9478ff00-393c-11ea-899e-eebd3a8e1c63.png)
Again, going with a filter with a smaller number of 203 taps we get a result where the expected equioscillations are visible:

![firpm203_ 1_1 01_0_0](https://user-images.githubusercontent.com/12035795/72619116-e15cd580-393c-11ea-94a9-65333036be70.png)
What is troublesome here though is the behavior in the [0.0534, 0.1468] transition region. You can clearly see an overshoot there and from what I know, you generally want to avoid those. To get rid of it, another approach that can handle constraints in the transition region needs to be used. For instance, I know of METEOR, a linear programming-based approach, that can also handle constraints in the transition region (see for instance https://www.cs.princeton.edu/~ken/meteor)

For the firpm-tc-50ka with magnitude vector I get similar frequency response plots for the 483 and 203 flter tap cases.

**Comment by jlwehle** [comment]
Thanks for looking at this and the pointer to METEOR.  You mention:

>   The filter specifications are a bit peculiar, ...
> 
>   What is troublesome here though is the behavior in the [0.0534, 0.1468]
>   transition region. You can clearly see an overshoot there ...
> 

I have some flexibility in the placement of the stopband.  What I'm not clear on is looking just at the filter specification is there something unusual that I've done?  Is there some restriction regarding using Parks-McClellan that I'm not being sensitive to when creating the filter specification?

**Comment by jlwehle** [comment]
I can estimate the minimum stop band left edge based on:

`  https://dsp.stackexchange.com/questions/31066/how-many-taps-does-an-fir-filter-need/31210#31210`

simply by re-arranging Fred Harris rule of thumb and solving for Fstop.

Is there a way to estimate the maximum allowable stop band left edge that avoids the overshoot?

**Comment by sfilip** [comment]
Not sure I can provide satisfactory answers to your questions, but I'll try. 

Transition band anomalies with Parks-McClellan generally tend to happen for multi band filters (with more than two bands) cases when the size of the transition band is close in length or larger than adjacent pass/stop bands. The initial example is peculiar (at least for me) because you are imposing different values for the pass band edges (namely 1.0 and 1.01). This is what is causing the overshoot to appear, even though you are targeting a two band filter. If you just take the pass band edges to be 1.0 and 1.0, there is no overshoot (as you can see in my previous comment).

I don't know of a bulletproof solution that will help you avoid overshoots. I would either suggest you use the same amplitude value for the band edges (which should be sufficient for low/high pass filters) or systematically change one or more of the band edges, filter length or the weighting function, redesign the filter and check if the overshoot is still present.

**Comment by jlwehle** [comment]
Thanks ... that provided me with a better understanding of how the problem can occur and reinforced the notion that filter design is an iterative process.

 I had naviely thought to maximize the transition band in order to reduce the ripple not realizing that too large of a transition band can cause problems.

**Comment by sfilip** [comment]
No problem. 

With the changes corresponding to #12 there is now an exception raised when such NaN problems occur for the final result. The displayed message in this case suggests how some parameters might be tweaked to cope with the issue. I have so far only been able to generate examples with different amplitude values inside a band where this happens.

**Comment by jlwehle** [comment]
Yep ... using the new code I see the exception.

Thanks.
